### ISSUE TITLE
What is the format of the NOTAM text？

### ISSUE THREAD

**Issue by Spacesky2022** [johnathanfernandes/AutoNOTAM#1]
Thank you for sharing.
What is the format of the NOTAM text？Can you share a screenshot? thank you！

**Comment by johnathanfernandes** [comment]
Hey! I've attached a sample NOTAM obtained from [here](https://notams.aim.faa.gov/notamSearch/nsapp.html#/) since I'm not too sure I can share the ones used to develop this application. The format should be the same, however.

![notepad++_2021-02-13_12-17-33](https://user-images.githubusercontent.com/66898724/107845528-8d4d4a80-6df5-11eb-9404-a652546b6f2f.png)
